<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TUP.Mundial.Datos\TUP.Mundial.Datos.csproj" />
    <ProjectReference Include="..\TUP.Mundial.Entidades\TUP.Mundial.Entidades.csproj" />
  </ItemGroup>

</Project>
